name: Build and Deploy Lambdas
on: 
  push:
    paths:
      - src/**

jobs:
  CI:
    name: Build/Deploy Poller
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "src/poller"
        
    steps: 
    - uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v main.go -o poller

    - name: Zip Pkg
      run: zip -j deploy.zip poller

    - name: Upload Zip
      run: aws lambda update-function-code --function-name poller --zip-file fileb://deploy.zip